title:	 	Die Friedliche Revolution im Stasi-Knast
markdown: 	kramdown
exclude: 	['README.md']
# url:		http://foerderverein-gedenkstaette-bautzen.de/revolution89/
url:		http://localhost:4000
permalink:	/:categories/:title/